### ISSUE TITLE
朝会2024/10/15

### ISSUE THREAD

**Issue by fukuda0801** [y4edd/sonic-journey#10]
2024-10-15(火)
朝会の前に、各々下記テンプレートに沿ってコメントを投稿してください.
共有事項があれば、こちらに記載してください.

```
#### 名前

#### やったこと、やっていること、全体に対しての進捗

#### これからやること確認

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
```

**Comment by fukuda0801** [comment]
#### 名前
- 福田 優斗
#### やったこと、やっていること、全体に対しての進捗
- トップページ　スライダー、曖昧検索、コンテンツタイトル作成
- テスト一部実施

#### これからやること確認
- シングルランキングなど

#### 困っていること、懸念点、相談
- 特になし

#### 共有事項（あれば）
- トップページ作成にあたってライブラリを複数追加しました。

**Comment by y4edd** [comment]
#### 名前
八重田　雄翔
#### やったこと、やっていること、全体に対しての進捗
【やったこと】
なし
【やっていること】
ZOD、Auth0、ReactHookのセットアップ
#### これからやること確認
上記の通り
#### 困っていること、懸念点、相談
なし
#### 共有事項（あれば）

**Comment by Kaito1290** [comment]
#### 名前
小野

#### やったこと、やっていること、全体に対しての進捗
- App Routerのキャッチアップ

#### これからやること確認
- マイページの作成

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by shotaniguchi** [comment]
#### 名前
- 谷口翔

#### やったこと、やっていること、全体に対しての進捗
- ヘッダー部一部作成
  - ヘッダー内ハンバーガーのレイアウト作成

#### これからやること確認
- ヘッダーのコード記述

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by mozamoza515** [comment]
#### 名前

北村大地

#### やったこと、やっていること、全体に対しての進捗

検索結果ページを作成中

#### これからやること確認

引き続き

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
