### ISSUE TITLE
朝会 2024-10-29

### ISSUE THREAD

**Issue by y4edd** [y4edd/sonic-journey#50]
2024-10-29(火)
朝会の前に、各々下記テンプレートに沿ってコメントを投稿してください.
共有事項があれば、こちらに記載してください.
```
#### 名前

#### やったこと、やっていること、全体に対しての進捗

#### これからやること確認

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
```

**Comment by fukuda0801** [comment]
#### 名前
福田 優斗
#### やったこと、やっていること、全体に対しての進捗
- ユーザー機能

#### これからやること確認
- useContext useReducer Redux学習(Reduxを取り入れたい。)

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by shotaniguchi** [comment]
#### 名前
- 谷口翔

#### やったこと、やっていること、全体に対しての進捗
- 特集ページの完成

#### これからやること確認
- ジャンルページ作成

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by y4edd** [comment]
#### 名前
八重田　雄翔
#### やったこと、やっていること、全体に対しての進捗
ログイン、ログアウトapi実装
#### これからやること確認
上記に同じ
#### 困っていること、懸念点、相談
なし
#### 共有事項（あれば）
よろしくお願いします。

**Comment by Kaito1290** [comment]
#### 名前
小野

#### やったこと、やっていること、全体に対しての進捗
プレイリストページの作成

#### これからやること確認
DBへのデータ保存処理

#### 困っていること、懸念点、相談
なし

#### 共有事項（あれば）
なし

**Comment by mozamoza515** [comment]
#### 名前

北村大地

#### やったこと、やっていること、全体に対しての進捗

アルバムのあいまい検索の表示

#### これからやること確認

アルバムのあいまい検索

#### 困っていること、懸念点、相談

すべて表示してから絞り込む？

#### 共有事項（あれば）
