### ISSUE TITLE
[ds] 朝会 2024-11-14

### ISSUE THREAD

**Issue by fukuda0801** [y4edd/sonic-journey#73]
## 2024-11-14 (木)

朝会の前に、各々下記テンプレートに沿ってコメントを投稿してください.
共有事項があれば、こちらに記載してください.

```markdown
### 名前

#### やったこと、やっていること、全体に対しての進捗

#### これからやること確認

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
```

**Comment by fukuda0801** [comment]
### 名前
福田 優斗
#### やったこと、やっていること、全体に対しての進捗
- 楽曲試聴表示コンポーネント作成
- 試聴履歴保存、更新、削除処理作成（アクション）

#### これからやること確認
- PR修正
- 試聴履歴表示機能作成

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
- PR作成しましたので、確認よろしくお願いします。

**Comment by shotaniguchi** [comment]
### 名前
- 谷口翔

#### やったこと、やっていること、全体に対しての進捗
- プレイリスト名変更機能作成

#### これからやること確認
- テストコード作成、PR作成

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by y4edd** [comment]
### 名前
八重田雄翔
#### やったこと、やっていること、全体に対しての進捗
【やったこと】
- ログイン状態の確認機能、フロントエンド側の実装
- PR指摘事項修正
#### これからやること確認
- ログアウトのフロントエンド側の実装（ボタンが反応しないので、、、）
#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by Kaito1290** [comment]
### 名前
- 小野

#### やったこと、やっていること、全体に対しての進捗
- お気に入り楽曲取得機能の実装
https://github.com/y4edd/sonic-journey/pull/71

#### これからやること確認
- ユーザーidの取得関数をどうするか

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by y4edd** [comment]
> ### 名前
> 八重田雄翔
> 
> #### やったこと、やっていること、全体に対しての進捗
> 【やったこと】
> 
> * ログイン状態の確認機能、フロントエンド側の実装
> * PR指摘事項修正
> 
> #### これからやること確認
> * ログアウトのフロントエンド側の実装（ボタンが反応しないので、、、）
> 
> #### 困っていること、懸念点、相談
> #### 共有事項（あれば）
