### ISSUE TITLE
[enhancement] ユーザー登録、ログイン後の通知

### ISSUE THREAD

**Issue by fukuda0801** [y4edd/sonic-journey#74]
## 課題
ユーザーを登録、ログインした際にログイン画面に遷移するだけですと、、登録が成功したかどうか利用者がわかりません。

## 解決策
トーストなどなんでも良いのですが、UIで確認できると良いと思います。

## 代替案

> あなたが検討した代替案や機能について, 明確かつ簡潔に説明してください.

## 補足情報

> 補足情報やスクリーンショットを機能要求に関して追加することができます.

**Comment by y4edd** [comment]
対応済です(2024/11/25)
