### ISSUE TITLE
[ds] 朝会 2024-11-15

### ISSUE THREAD

**Issue by fukuda0801** [y4edd/sonic-journey#75]
## 2024-11-15 (金)

朝会の前に、各々下記テンプレートに沿ってコメントを投稿してください.
共有事項があれば、こちらに記載してください.

```markdown
### 名前

#### やったこと、やっていること、全体に対しての進捗

#### これからやること確認

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
```

**Comment by fukuda0801** [comment]
### 名前
福田 優斗
#### やったこと、やっていること、全体に対しての進捗
- 試聴履歴保存処理作成
#### これからやること確認
- 試聴履歴に基づく楽曲をページに表示させる
#### 困っていること、懸念点、相談

#### 共有事項（あれば）
- PR確認よろしくお願いします。

**Comment by shotaniguchi** [comment]
### 名前
- 谷口翔

#### やったこと、やっていること、全体に対しての進捗
- プレイリスト一覧機能単体テスト作成

#### これからやること確認
- PR作成
- プレイリスト詳細画面作成

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by y4edd** [comment]
### 名前
八重田雄翔
#### やったこと、やっていること、全体に対しての進捗
【やったこと】
- ログイン状態の確認処理
- マイページからログアウトするときの処理
【やっていること】
- ユーザ情報編集api実装
#### これからやること確認
【やっていること】に同じ
#### 困っていること、懸念点、相談

#### 共有事項（あれば）
よろしくお願いいたします。

**Comment by Kaito1290** [comment]
### 名前
小野魁士

#### やったこと、やっていること、全体に対しての進捗
- サーバーサイドからログインしているか確認する関数を作成
- cookieからtokenを取得するユーティリティ関数を修正

#### これからやること確認

#### 困っていること、懸念点、相談
- `src/app/mypage/favoritesong/page.tsx`ログインが必要なときのhttpステータスコードを401にしたい。

#### 共有事項（あれば）
