### ISSUE TITLE
[ds] 朝会 2024-11-18

### ISSUE THREAD

**Issue by Kaito1290** [y4edd/sonic-journey#80]
## yyyy-MM-dd (E)

朝会の前に、各々下記テンプレートに沿ってコメントを投稿してください.
共有事項があれば、こちらに記載してください.

```markdown
### 名前

#### やったこと、やっていること、全体に対しての進捗

#### これからやること確認

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
```

**Comment by Kaito1290** [comment]
### 名前
小野

#### やったこと、やっていること、全体に対しての進捗
- お気に入りアーティスト取得機能の実装

#### これからやること確認
- お気に入り楽曲・アーティストの動作確認できるように初期データを挿入するSQLを書く

#### 困っていること、懸念点、相談

#### 共有事項（あれば）

**Comment by y4edd** [comment]
### 名前
八重田雄翔
#### やったこと、やっていること、全体に対しての進捗
【やったこと】
- ユーザー情報編集機能の作成(PR作成済み、レビュー待ち)
- ユーザ情報表示機能、ページ作成
【やっていること】
- ユーザー情報表示ページ(退会用のモーダル作成)
- 各種単体テスト
#### これからやること確認
【やっていること】に同じ
#### 困っていること、懸念点、相談
APIを、「getUserInfo(ユーザーのemail、userNameを取得するAPI)」「checkLogin(トークンの有無、userIDを取得するAPI)」の二つを作成しました。
取得するものが被ってきている気がするので一つにすべきか悩んでいます。
#### 共有事項（あれば）
- 寒くなってきたのでご自愛ください

**Comment by mozamoza515** [comment]
### 名前

北村大地

#### やったこと、やっていること、全体に対しての進捗

あいまい検索結果のアーティスト結果の表示

#### これからやること確認

あいまい検索結果のアーティスト結果の表示

#### 困っていること、懸念点、相談

#### 共有事項（あれば）
